eReolen/base

sites/all/modules/reol_loan/reol_loan.module

Fixes “Array to string conversion” notice – and makes the display of “loans” actually work – when a “loan text” is defined.

ER-487: Fixed display of “loan text”

---

sites/all/modules/reol_reservation/reol_reservation.module

The checkboxes under “Reservationer klar til lån” are `disabled`, i.e. their values are not `POST`'ed  when clicking “Slet valgte reservationer”. 
This fixed that issue.

ER-535: Removed disabling of reservation checkboxes

---

sites/all/modules/reol_statistics/reol_statistics.module

The `collect`ion of data may skip data at the end of a month†. This fixes this.
† If `cron` run daily at 08:00, say, all loans after 08:00 on the last day of the month will not be included in the collected data because we're collection from "next month" too early.

SUPPORT-2006: Fixed loop

---

sites/all/modules/reol_feed/includes/reol_feed.carousel.inc
sites/all/modules/reol_feed/includes/reol_feed.categories.inc
sites/all/modules/reol_feed/includes/reol_feed.frontpage.inc
sites/all/modules/reol_feed/reol_feed.module

This is a patch/hack to resurrect to old app feeds since The New Android App™ is not yet ready. For performance reasons we only get 50 results (in a quick 'n dirty way) for each carousel search.

ER-544: Resurrected old app feeds

---

sites/all/modules/reol_widget/src/Controller/SearchController.php

Add sorting (with sensible default) to widget search results. We'll switch to SAL in a later pull request.

ER-569: Added search result sorting

---

sites/all/modules/publizon/lib/storage/PublizonChecklistItem.class.inc

https://jira.itkdev.dk/browse/ER-618
For performance reasons, the “loanstatus” property will be removed from the pubhub service. eReolen don't use it for anything regarding checklists (“Huskelister”).

ER-618: Removed loanStatus from checklist item

---

sites/all/modules/publizon/includes/publizon.availability.inc

https://jira.itkdev.dk/browse/DEVSUPP-209
We may cache non-anonymous availability statuses. All cached availabily information should be anonymous.
This issue was apparently introduced in https://github.com/eReolen/base/commit/cb62f1c43b873637ce564e8932f126251a2dda94#diff-22b9646d6995bc9bc118f70f57022ea9R91.

DEVSUPP-209: Fixed issue with cached availability

---

sites/all/modules/reol_prevent_unpublish/includes/reol_prevent_unpublish.admin.inc
sites/all/modules/reol_prevent_unpublish/reol_prevent_unpublish.info
sites/all/modules/reol_prevent_unpublish/reol_prevent_unpublish.install
sites/all/modules/reol_prevent_unpublish/reol_prevent_unpublish.module

Ticket: https://jira.itkdev.dk/browse/ER-1072
1. Always set node `status = 1` for nodes in prevent list on node save (to lock it down).
2. Prevent un-check in node edit form (to show user that is can not be unpublished).
3. Very simple administrative UI.

ER-1072: Added new prevent unpublish module

---

sites/all/themes/orwell/templates/system/html.tpl.php

https://jira.itkdev.dk/browse/ER-1132
Adds `lang` attribute to the `html` element (in addition to the already existing `xml:lang` attribute).

ER-1132: Added lang attribute to html element

---

sites/all/themes/orwell/templates/node/node--article--view-mode--teaser--image.tpl.php

https://jira.itkdev.dk/browse/ER-1149
* Remove the preheader/label text
* Change button text to read more

ER-1149: make theme texts translatable

---

profiles/ding2/modules/ting_covers/ting_covers.module
sites/all/modules/publizon/lib/client/PublizonProductClient.class.inc
sites/all/modules/publizon/publizon.info
sites/all/patches/ting_covers-ting_covers_fetch_image-guzzle.patch

https://jira.itkdev.dk/browse/SUPP0RT-262
Using drupal_http_request to download cover images will load the image data into memory and possibly exceed PHP's memory limit. Using Guzzle we can download the image data directly to a (temporary) file.

SUPP0RT-262: Optimize cover image download

---

sites/all/modules/reol_app_feeds/reol_app_feeds.drush.inc

https://jira.itkdev.dk/browse/SUPP0RT-266
It seems that the autoloader has not been initialized when functions implementing `hook_drush_command` are invoked. Therefore use of `FeedHelper::$feedNames` in this hook is replaced with a `--list` option.

SUPP0RT-266: Added feed list option

---

.github/workflows/push.yaml

Adds GitHub Action to check that theme assets are up to date when pushing (by merging a pull request) to the `develop` branch.

GitHub Actions: Check themes assets

---

sites/all/modules/media_videotool/includes/MediaInternetVideoToolHandler.inc
sites/all/modules/media_videotool/includes/MediaVideoToolStreamWrapper.inc
sites/all/modules/media_videotool/media_videotool.module
sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php

https://jira.itkdev.dk/browse/ER-1268
- ER-1268: Changed key “hls_url” to “hlsUrl” in feed
- ER-1268: Switched to https in Videotool media urls

ER-1268: Miscellaneous

---

robots.txt

https://jira.itkdev.dk/browse/SUPP0RT-379
Google (and possibly others search engines) has managed to index some login paths.

SUPP0RT-379: Disallowed indexing of login paths

---

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php

https://jira.itkdev.dk/browse/ER-1296
Always use `image` as `view` in feed.

ER-1296: Fixed view in feed

---

sites/all/modules/ereol_article/ereol_article.features.field_instance.inc

https://jira.itkdev.dk/browse/ER-1296
Sets article summary trim length to 120.

ER-1296: Fixed article summary length

---

sites/all/modules/reol_use_loan/reol_use_loan.module

https://jira.itkdev.dk/browse/ER-1253
The general styling of eReolen flows into the reader. This fixes that by throwing away all CSS not related to the reader on the reader page.

ER-1253: Removed superfluous CSS from reader page

---

sites/all/modules/reol_frontend/plugins/content_types/library_info.inc
sites/all/modules/reol_frontend/reol_frontend.info

https://jira.itkdev.dk/browse/ER-1193
Adds info on current number of loans.
Before
After (missing Danish translation)

ER-1193: Added info on current number of loans

---

sites/all/modules/reol_frontend/plugins/content_types/library_info.inc
sites/all/themes/wille/templates/user/library_info.tpl.php

https://jira.itkdev.dk/browse/ER-1193
Updated display of loans and max loans on GO. Breaks all rules for how to build translatable strings with "n of m" placeholders – but it works!

ER-1193: Updated display on GO

---

sites/all/modules/reol_frontend/plugins/content_types/library_info.inc

https://jira.itkdev.dk/browse/SUPP0RT-737
Uses quota loan data to show the number of loans, but only on eReolen where the quota information is readily available.
Automatic checks fails due to errors that are fixed in https://github.com/eReolen/base/pull/290.

SUPP0RT-737: Added quota loan data on eReolen

---

sites/all/modules/publizon/includes/publizon.admin.inc
sites/all/modules/publizon/includes/publizon.auth.inc

https://jira.itkdev.dk/browse/ER-1432
Makes it possible to alias a municipality to another municipality. The aliases can be edited with `drush`:
```sh
drush variable-set publizon_municipality_aliases --format=json '{"563": "561"}'
```
or on `/admin/config/ding/provider/publizon` (cf. screenshot).
This is a hack!

ER-1432: Municipality aliases

---

sites/all/modules/reol_base/reol_base.module

https://jira.itkdev.dk/browse/SUPP0RT-836
Some items in Brønden have only a single media type, e.g.
```xml
<dc:type xsi:type="dkdcplus:BibDK-Type">E-bog</dc:type>
```
whereas others (most?) have more media types, e.g.
```xml
<dc:type xsi:type="dkdcplus:BibDK-Type">Billedbog (net)</dc:type>
<dc:type xsi:type="dkdcplus:BibDK-Type">E-bog</dc:type>
```
This change adds "E-bog" to the types defined in [_reol_base_get_types](https://github.com/eReolen/base/blob/develop/sites/all/modules/reol_base/reol_base.module#L737-L822).
See https://jira.itkdev.dk/browse/SUPP0RT-836?focusedCommentId=44811&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-44811 for further details.
If your code does not pass all the requirements on the checklist you have to add a comment …

SUPP0RT-836: Handled media type "e-bog"

---

profiles/ding2/modules/ding_adgangsplatformen/ding_adgangsplatformen.module
profiles/ding2/modules/ding_adgangsplatformen/includes/ding_adgangsplatformen.admin.inc

https://jira.itkdev.dk/browse/ER-1425
Added agency type to single signon to only show "folkebiblioteker" in the library selection dropdown.
N/A

ER-1425: Added agencytype=folk to login url

---

sites/all/modules/publizon/publizon.features.field_base.inc
sites/all/modules/publizon/publizon.features.field_instance.inc
sites/all/modules/publizon/publizon.features.inc
sites/all/modules/publizon/publizon.info
sites/all/modules/publizon/publizon.strongarm.inc
sites/all/modules/reol_frontend/reol_frontend.module
sites/all/modules/reol_loan/reol_loan.module

https://jira.itkdev.dk/browse/ER-1444
Adds confirm fields for phone and email on user profile and validates that values are confirmed correctly.
A message about why the confirmation is need can be set on `/admin/config/people/accounts` » Profile confirm message
(Missing translation of error message)

ER-1444: Confirm profile data

---

sites/all/modules/reol_loan/reol_loan.module
sites/all/themes/wille/templates/user/library_info.tpl.php

https://jira.itkdev.dk/browse/ER-1491
- Removes “out of” stuff from loans info (see screenshots)
- Fixes handling of ereol_loan_text
Before:
After:

ER-1491: Remove “out of” stuff from loans info

---

sites/all/modules/reol_app_feeds/src/Feed/FrontPageFeed.php
sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php

https://jira.itkdev.dk/browse/SUPP0RT-1234
Fixes issue with using wrong node type (bundle) to get latest news.
The “[Cleaned up](https://github.com/eReolen/base/pull/328/commits/2de7ed15330e693d3e5467b97cd5d02e9cc2e2a9)" commit is not directly related to the issue, but is just an added bonus.

Latest news

---

sites/all/themes/wille/templates/ting/ting_object.tpl.php

https://jira.itkdev.dk/browse/SUPP0RT-1375
Hides ting relations (added in https://github.com/eReolen/base/pull/340) from object display.
Before (after https://github.com/eReolen/base/pull/340)
After (before https://github.com/eReolen/base/pull/340)

SUPP0RT-1375: Hid ting releations

---

sites/all/modules/publizon/publizon.module

https://leantime.itkdev.dk/#/tickets/showTicket/233
Shows submit button only if phone or email notification is visible.
None selected:
Phone notification selected:
Email notification selected:
Both selected:

Show submit button only if phone or email notification is visible
