profiles/ding2/modules/ding_user/ding_user.module, profiles/ding2/modules/opensearch/lib/ting-client/lib/request/TingClientCollectionRequest.php, profiles/ding2/modules/opensearch/lib/ting-client/lib/request/TingClientRequest.php, sites/all/modules/publizon/includes/publizon.availability.inc, sites/all/modules/publizon/includes/publizon.bookmark.inc, sites/all/modules/publizon/includes/publizon.loan.inc, sites/all/modules/publizon/includes/publizon.reservation.inc, sites/all/modules/publizon/includes/publizon.user.inc, sites/all/modules/publizon/publizon.module, sites/all/modules/reol_base/reol_base.module, sites/all/modules/reol_bookmark/reol_bookmark.module
* Fix cache id in opensearch (PR made to core and approved).
* Mostly wrappers in publizon provider to enable session cache.
* Static cache for availability in publizon provider.
=> ER-317: Fixed opensearch cache + session cache in provider

sites/all/modules/reol_feed/reol_feed.module
=> ER-319: Added newsletter feed

sites/all/themes/wille/templates/panels/breol_news_page.tpl.php, sites/all/themes/wille/templates/paragraphs/paragraphs-item--see-all-news-button.tpl.php
This should be released with https://github.com/eReolen/ereolengo/pull/1
- Prepares news page template to support news categorization
- Prepares news button template to allow linking to news categories.
=> ER-286: Changed templates to support english news setup

sites/all/modules/reol_loan/reol_loan.module
Added form alter to user_admin_settings_form
Added panels_pane_content_alter to user loan pane
=> ER-287: Added form alter and loan text

profiles/ding2/modules/opensearch/lib/ting-client/lib/request/TingClientCollectionRequest.php, profiles/ding2/modules/opensearch/lib/ting-client/lib/request/TingClientSearchRequest.php, profiles/ding2/modules/opensearch/opensearch.client.inc, sites/all/modules/reol_base/reol_base.module
https://itkdev.atlassian.net/browse/ER-426
=> ER-426: Cache issues

sites/all/modules/reol_field_carousel/reol_field_carousel.module
We have left the old code for future reference when we fix the issue for real.
=> ER-480: Fixed duplicates in carousel

sites/all/modules/publizon/publizon.module
Automatically fills in the user's support id in the support form.
=> ER-48: Added support_id default value

sites/all/modules/reol_base/reol_base.module, sites/all/modules/reol_frontend/reol_frontend.module
=> Revert "ER-489: Added debug statement to detected missing icons"

sites/all/modules/publizon/includes/publizon.availability.inc, sites/all/modules/publizon/includes/publizon.bookmark.inc, sites/all/modules/publizon/includes/publizon.loan.inc, sites/all/modules/reol_bookmark/reol_bookmark.module
Ticket: https://itkdev.atlassian.net/browse/ER-561
=> ER-561: Improved availability cache and bookmarks

sites/all/modules/publizon/includes/publizon.availability.inc, sites/all/modules/publizon/includes/publizon.bookmark.inc, sites/all/modules/publizon/includes/publizon.loan.inc, sites/all/modules/publizon/includes/publizon.reservation.inc, sites/all/modules/reol_loan/reol_loan.module, sites/all/modules/reol_reservation/reol_reservation.module, sites/all/modules/reol_use_loan/reol_use_loan.module
https://jira.itkdev.dk/browse/DDBTEAM-243
=> DDBTEAM-243: Support for user availability in buttons state

sites/all/modules/reol_lazy_load_images/reol_lazy_load_images.module
https://jira.itkdev.dk/browse/ER-152
Før:
Efter:
=> ER-152: Added images styles to handle pod-cast covers

README.md, profiles/ding2/modules/ding_adgangsplatformen/ding_adgangsplatformen.module, profiles/ding2/modules/ding_user/ding_user.module, sites/all/modules/publizon/includes/publizon.auth.inc, sites/all/modules/publizon/includes/publizon.default_error_messages.inc, sites/all/modules/publizon/publizon.classes.inc, sites/all/modules/publizon/publizon.install, sites/all/modules/publizon/publizon.module, sites/all/modules/reol_base/reol_base.module, sites/all/modules/reol_statistics/reol_statistics.module, sites/all/patches/ding_adgangsplatformen.patch, sites/all/patches/ding_user_extra.patch, sites/all/themes/pratchett/template.php
Ticket: https://jira.itkdev.dk/browse/DDBTEAM-168
=> DDBTEAM-167: Added support for adgangsplatformen

sites/all/modules/reol_statistics/reol_statistics.module
https://jira.itkdev.dk/browse/ER-623
This improves collection of loan statistics from UNI•Login users.
Depends on changes made in https://github.com/eReolen/ereolengo/pull/4
=> ER-623: UNI•Login improvements

sites/all/modules/publizon/includes/publizon.loan.inc, sites/all/modules/publizon/lib/client/PublizonLoanClient.class.inc
https://jira.itkdev.dk/browse/ER-633
=> ER-633: Added institution id to create loan

README.md, profiles/ding2/modules/ding_test/composer.json, profiles/ding2/modules/ding_test/composer.lock, profiles/ding2/modules/ding_test/ding_test.info, profiles/ding2/modules/ding_test/ding_test.module, profiles/ding2/modules/ding_test/src/DingUnitTestBase.php, sites/all/patches/ding_test.patch
Needed to run tests from https://github.com/eReolen/ereolengo/pull/5
=> ER-682: Added ding_test module

sites/all/modules/reol_frontend/reol_frontend.module
https://jira.itkdev.dk/browse/ER-721
=> ER-721: Added check for non-empty icon

sites/all/modules/publizon/includes/publizon.loan.inc
https://jira.itkdev.dk/browse/ER-693
=> ER-693: Added check for valid institution on loan create

sites/all/modules/reol_app_feeds/README.md, sites/all/modules/reol_app_feeds/includes/reol_app_feeds.admin.inc, sites/all/modules/reol_app_feeds/reol_app_feeds.admin.inc, sites/all/modules/reol_app_feeds/reol_app_feeds.features.inc, sites/all/modules/reol_app_feeds/reol_app_feeds.info, sites/all/modules/reol_app_feeds/reol_app_feeds.install, sites/all/modules/reol_app_feeds/reol_app_feeds.module, sites/all/modules/reol_app_feeds/src/Controller/DefaultController.php, sites/all/modules/reol_app_feeds/src/Feed/AbstractFeed.php, sites/all/modules/reol_app_feeds/src/Feed/CategoriesFeed.php, sites/all/modules/reol_app_feeds/src/Feed/FrontPageFeed.php, sites/all/modules/reol_app_feeds/src/Feed/ThemesFeed.php, sites/all/modules/reol_app_feeds/src/Helper/NodeHelper.php, sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php, sites/all/modules/reol_base/reol_base.info, sites/all/modules/reol_base/reol_base.install, sites/all/modules/reol_base/reol_base.module
https://jira.itkdev.dk/browse/ER-641
This is mostly a copy of https://github.com/eReolen/ereolen/tree/develop/ereol_app_feeds with a few changes to fit the new category app feed and some hacks to make content from eReolen Go! fit into the feeds.
Relates to https://github.com/eReolen/ereolen/pull/18 and https://github.com/eReolen/ereolengo/pull/7
=> App feeds (v2) for both eReolen and eReolen Go!

sites/all/modules/reol_statistics/reol_statistics.admin.inc, sites/all/modules/reol_statistics/reol_statistics.pages.inc
https://jira.itkdev.dk/browse/ER-734
From 2020-01-01 all collection and display of statistics are handled by Publizon.
=> ER-734: Disabled display of statistics from 2020

sites/all/modules/reol_app_feeds/src/Helper/NodeHelper.php
https://jira.itkdev.dk/browse/ER-763
=> ER-763: Fixed handling of images in feeds

sites/all/modules/publizon/publizon.module
https://jira.itkdev.dk/browse/ER-775
=> ER-775: Added expire time to client library cache

.docker/vhost.conf, sites/all/modules/reol_base/reol_base.install, sites/all/modules/reol_base/reol_base.module
Ticket: https://jira.itkdev.dk/browse/ER-780
=> ER-780: Changed search input field max-length to 2048

sites/all/modules/reol_app_feeds/src/Feed/FrontPageFeed.php, sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-779
=> ER-779: Fixed handling of videos in feed

profiles/ding2/modules/opensearch/includes/opensearch.search.inc, sites/all/modules/publizon/lib/PublizonClient.class.inc, sites/all/patches/opensearch-isPartOf-null-dereference.patch
https://jira.itkdev.dk/browse/ER-777
=> ER-777: Null dereference and missing exception message

sites/all/modules/reol_app_feeds/includes/reol_app_feeds.admin.inc, sites/all/modules/reol_app_feeds/reol_app_feeds.install, sites/all/modules/reol_app_feeds/src/Feed/FrontPageFeed.php, sites/all/modules/reol_app_feeds/src/Helper/NodeHelper.php, sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-781
=> ER-781: Frontpage feed content order

profiles/ding2/modules/opensearch/includes/opensearch.search.inc, sites/all/patches/opensearch-autocomplete.patch
https://jira.itkdev.dk/browse/ER-782
=> ER-782: Made search suggestions work

sites/all/modules/reol_base/reol_base.module
https://jira.itkdev.dk/browse/ER-782
=> ER-782: Disabled search autocomplete

profiles/ding2/modules/opensearch/includes/opensearch.search.inc, sites/all/patches/opensearch-autocomplete.patch
=> Revert "ER-782: Made search suggestions work"

sites/all/modules/reol_base/reol_base.module
https://jira.itkdev.dk/browse/DEVSUPP-223
=> DEVSUPP-223: Added autocomplete hack

sites/all/modules/reol_base/reol_base.module
https://jira.itkdev.dk/browse/ER-794
=> ER-794: Disabled built-in autocomplete

profiles/ding2/modules/opensearch/opensearch.module
https://jira.itkdev.dk/browse/ER-810
=> ER-810: Added boost changes from DDB Core

docker-compose.yml, profiles/ding2/modules/ting/ting.module, sites/all/modules/overdrive/overdrive.module, sites/all/modules/paragraphs/reol_audio_preview_paragraph/reol_audio_preview_paragraph.module, sites/all/modules/reol_base/reol_base.module, sites/all/patches/error-missing-record.patch
Ticket: https://jira.itkdev.dk/browse/ER-815
It seams that somethings have changed in datawell 5.2 in relations to records that no longer exits which hits eReolen reference lists and some of the checks and changes we have.
It also seams that the core modules throws some error when error reporting is enabled, but I thing that DDB Core should fix these.
=> Fixed issues that give http 500 error in new relic

profiles/ding2/modules/ding_loan/plugins/content_types/loans.inc, profiles/ding2/modules/ting/ting.module, sites/all/modules/publizon/publizon.module, sites/all/modules/reol_base/reol_base.module, sites/all/modules/reol_loan/reol_loan.module, sites/all/modules/reol_use_loan/reol_use_loan.module, sites/all/patches/error-missing-record.patch
https://jira.itkdev.dk/browse/ER-829
=> Fixes errors related to data well 5.2

sites/all/modules/contrib/publication_date/CHANGELOG.txt, sites/all/modules/contrib/publication_date/LICENSE.txt, sites/all/modules/contrib/publication_date/README.txt, sites/all/modules/contrib/publication_date/includes/publication_date.admin.inc, sites/all/modules/contrib/publication_date/includes/publication_date.views.inc, sites/all/modules/contrib/publication_date/publication_date.api.php, sites/all/modules/contrib/publication_date/publication_date.ds_fields_info.inc, sites/all/modules/contrib/publication_date/publication_date.info, sites/all/modules/contrib/publication_date/publication_date.install, sites/all/modules/contrib/publication_date/publication_date.module, sites/all/modules/contrib/publication_date/publication_date.tokens.inc, sites/all/modules/contrib/publication_date/tests/publication_date.test, sites/all/modules/reol_app_feeds/reol_app_feeds.info, sites/all/modules/reol_app_feeds/reol_app_feeds.install, sites/all/modules/reol_app_feeds/reol_app_feeds.module, sites/all/modules/reol_app_feeds/src/Feed/ThemesFeed.php
https://jira.itkdev.dk/browse/ER-816
=> ER-816: Order themes by publication date in feed

sites/all/modules/reol_app_feeds/src/Feed/FrontPageFeed.php
https://jira.itkdev.dk/browse/ER-632
=> ER-632: Prepend latest news to frontpage feed themes

sites/all/modules/smartbanner/includes/smartbanner.admin.inc, sites/all/modules/smartbanner/smartbanner.module
https://jira.itkdev.dk/browse/ER-830
Bug fixes.
=> ER-830: Bug fixes

sites/all/modules/reol_app_feeds/src/Helper/NodeHelper.php, sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/DEVSUPP-285
=> DEVSUPP-285: Handled audio data in paragraphs in feed

.env
https://jira.itkdev.dk/browse/ER-948
=> ER-948: Changedserver reference

sites/all/modules/reol_loan/includes/reol_loan.loan.inc
https://jira.itkdev.dk/browse/ER-986
=> ER-986: Removed function argument type hint

README.md, profiles/ding2/modules/opensearch/src/OpenSearchTingObject.php, sites/all/patches/opensearch-dkdcplus-DBCO.patch
https://jira.itkdev.dk/browse/ER-944
Includes dkdcplus:DBCO subjects in tag lists on publications.
=> ER-944: dkdcplus:DBCO subjects

sites/all/modules/contrib/web_accessibility_statement/README.md, sites/all/modules/contrib/web_accessibility_statement/composer.json, sites/all/modules/contrib/web_accessibility_statement/web_accessibility_statement.inc, sites/all/modules/contrib/web_accessibility_statement/web_accessibility_statement.info, sites/all/modules/contrib/web_accessibility_statement/web_accessibility_statement.module, sites/all/modules/reol_base/reol_base.install
https://jira.itkdev.dk/browse/ER-995
Adds web_accessibility_statement module (https://github.com/itk-dev/web_accessibility_statement/tree/d7-master).
=> Web accessibility statement

sites/all/themes/wille/template.php
https://jira.itkdev.dk/browse/ER-989
=> ER-989: Fixed path to organic.svg

sites/all/modules/contrib/web_accessibility_statement/web_accessibility_statement.info
https://jira.itkdev.dk/browse/ER-1003
=> ER-1003: web_accessibility_statement info

sites/all/modules/itk_cookieinformation/itk_cookieinformation.module
https://jira.itkdev.dk/browse/ER-1047
=> ER-1047: Clean up cookie module

sites/all/themes/wille/template.php
Ticket: https://jira.itkdev.dk/browse/ER-1065
Side med collection: http://ereolen.local.itkdev.dk/ting/collection/150061-netlydbog%3AODN0003452063
=> ER-1065: Change collection links to point object

sites/all/modules/reol_app_feeds/src/Feed/CategoriesFeed.php
https://jira.itkdev.dk/browse/ER-1105
Adds elements with `"type": "video"` to `"subcategories"`:
```json
[
{
"guid": "790",
"type": "category",
"title": "ER-1105",
"color": "#fedfed",
"imageUrl": "https://127.0.0.1:8000/sites/default/files/styles/app_feed_image/public/lorempixel-500x500-04.png?itok=seX-o--y",
"query": "ER-1105",
"subcategories": [
{
"guid": "424",
"type": "video",
"title": "Biologiundervisning fra Randers Regnskov",
"image": "",
"source": "youtube",
"url": "https://www.youtube.com/watch?v=vh5e89GQoUg"
}
]
}
]
```
=> ER-1105: Added videos to categories feed

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1103
=> ER-1103: Allow more identifiers

sites/all/modules/reol_statistics/reol_statistics.pages.inc
https://jira.itkdev.dk/browse/SUPP0RT-125
=> SUPP0RT-125: Included statistics before final year

sites/all/modules/reol_app_feeds/src/Helper/NodeHelper.php, sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1129
Adds check for null value before using array functions on value.
Lowers max number of search results in categories feed (to prevent memory exhaustion).
=> ER-1129: Feed improvements

sites/all/modules/reol_lazy_load_images/reol_lazy_load_images.module
https://jira.itkdev.dk/browse/ER-1134
=> ER-1134: Added ARIA label to images

sites/all/themes/pratchett/template.php, sites/all/themes/wille/template.php
https://jira.itkdev.dk/browse/ER-1133
=> ER-1133: Updated viewport to not prevent zoom

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1126
Fixes handling of video source in feed.
=> ER-1126: Fixed handling of video source in feed

README.md, robots.txt, sites/all/patches/robots-content-unilogin.patch
https://jira.itkdev.dk/browse/SUPP0RT-151
=> SUPP0RT-151: Disallowed indexing of /content/unilogin

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1122
This reverts commit cdcbaa6962bb166c49ff8c59173eeac1e1cb892d.
=> Revert "ER-1122: Added lead to feed"

sites/all/themes/orwell/templates/system/html.tpl.php
https://jira.itkdev.dk/browse/ER-1140
=> ER-1140: added tabindex to skiplink

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1129
Optimizes loading of carousel identifiers.
=> ER-1129: Optimized loading of carousel identifiers

sites/all/modules/publizon/lib/client/PublizonProductClient.class.inc
https://jira.itkdev.dk/browse/ER-1191
=> ER-1191: Optimized image download size

sites/all/modules/media_videotool/LICENSE.txt, sites/all/modules/media_videotool/README.md, sites/all/modules/media_videotool/README.txt, sites/all/modules/media_videotool/includes/MediaInternetVideoToolHandler.inc, sites/all/modules/media_videotool/includes/MediaVideoToolBrowser.inc, sites/all/modules/media_videotool/includes/MediaVideoToolStreamWrapper.inc, sites/all/modules/media_videotool/includes/media_videotool.formatters.inc, sites/all/modules/media_videotool/includes/media_videotool.variables.inc, sites/all/modules/media_videotool/includes/themes/media-videotool-video.legacy-example.tpl.php, sites/all/modules/media_videotool/includes/themes/media-videotool-video.tpl.php, sites/all/modules/media_videotool/includes/themes/media_videotool.theme.inc, sites/all/modules/media_videotool/js/media-videotool.browser.js, sites/all/modules/media_videotool/js/media_videotool.fromurl.js, sites/all/modules/media_videotool/media_videotool.info, sites/all/modules/media_videotool/media_videotool.install, sites/all/modules/media_videotool/media_videotool.module
https://jira.itkdev.dk/browse/ER-1229
Adds media_videotool module (cf. https://github.com/eReolen/ereolengo/pull/60).
=> ER-1229: Add media_videotool module

sites/all/modules/reol_app_feeds/reol_app_feeds.module, sites/all/modules/reol_app_feeds/src/Feed/FrontPageFeed.php, sites/all/modules/reol_app_feeds/src/Feed/V3/FrontPageFeed.php, sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1227
=> ER-1227: Front page feed v3

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1153
Fixes order of news items.
=> ER-1153: Fixed ordering of news items

sites/all/modules/reol_base/reol_base.module, sites/all/themes/pratchett/ckeditor/contents.css
https://jira.itkdev.dk/browse/ER-1147
Adds custom theme styling to wysiwyg editor.
=> ER-1147: Added custom wysiwyg styles

sites/all/themes/orwell/template.php, sites/all/themes/wille/template.php
https://jira.itkdev.dk/browse/ER-1197
Removes title from description.
=> ER-1197: Removed title

sites/all/modules/reol_app_feeds/reol_app_feeds.drush.inc, sites/all/modules/reol_app_feeds/src/Feed/V3/FrontPageFeed.php, sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1256
- ER-1256: Handled Blue titles info paragraph in feed
- ER-1256: Handled exception in feed generation
Depends on https://github.com/eReolen/ereolen/pull/41 and https://github.com/eReolen/ereolengo/pull/62
=> ER-1256: Blue titles info

sites/all/modules/media_videotool/includes/media_videotool.admin.inc, sites/all/modules/media_videotool/media_videotool.info, sites/all/modules/media_videotool/media_videotool.module, sites/all/modules/media_videotool/src/ApiClient.php, sites/all/modules/reol_app_feeds/reol_app_feeds.info, sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1268
Adds `hls_url` to Videotool video element in feed. Updates Videotool thumbnail url to point to a larger image.
- ER-1268: Added Videotool API client
- ER-1268: Added Videotool HLS urls in feed
- ER-1268: Updated Videotool thumbnail url in feed
=> ER-1268: Videotool hls url

sites/all/modules/reol_app_feeds/src/Feed/V3/FrontPageFeed.php
https://jira.itkdev.dk/browse/ER-1270
=> ER-1270: Added reviews in frontpage v3 feed

sites/all/modules/contrib/honeypot/LICENSE.txt, sites/all/modules/contrib/honeypot/README.md, sites/all/modules/contrib/honeypot/docker-compose.yml, sites/all/modules/contrib/honeypot/honeypot.admin.inc, sites/all/modules/contrib/honeypot/honeypot.api.php, sites/all/modules/contrib/honeypot/honeypot.info, sites/all/modules/contrib/honeypot/honeypot.install, sites/all/modules/contrib/honeypot/honeypot.module, sites/all/modules/contrib/honeypot/honeypot.test, sites/all/modules/contrib/honeypot/js/honeypot.js, sites/all/modules/contrib/honeypot/tests/honeypot_test.info, sites/all/modules/contrib/honeypot/tests/honeypot_test.module
Adds honeypot module.
Required by:
https://github.com/eReolen/ereolen/pull/44
https://jira.itkdev.dk/browse/ER-1251
=> ER-1251: Add honeypot module

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1256
Adds the missing link.
=> ER-1256: Added the missing link

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1307
=> ER-1307: Use null for no value

sites/all/modules/reol_base/reol_base.module, sites/all/modules/reol_bookmark/reol_bookmark.module, sites/all/modules/reol_loan/reol_loan.module, sites/all/modules/reol_use_loan/reol_use_loan.module
https://jira.itkdev.dk/browse/ER-1278
Fixed order of ding_entity_buttons implementations to make sure that buttons come in the required order.
=> ER-1278: Fixed button order

sites/all/modules/ereol_article/ereol_article.features.field_instance.inc
https://jira.itkdev.dk/browse/ER-1296
=> ER-1296: Made subject optional on article

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1334
=> ER-1334: Video bundle feed

sites/all/modules/reol_frontend/reol_frontend.module
https://jira.itkdev.dk/browse/ER-1349
=> ER-1349: Remove duplicated facet options

sites/all/modules/ereol_article/ereol_article.features.field_instance.inc, sites/all/modules/ereol_article/ereol_article.module
https://jira.itkdev.dk/browse/ER-1356
Adds autocomplete (search) to promoted materials on video bundles.
=> ER-1356: Added autocomplete to promoted materials

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1333
Fixes color in feed by using correct field name.
=> ER-1333: Fixed color in feed

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1245
Handles getting identifiers from article carousels in app feeds.
=> ER-1245: Handled article carousels in feed

sites/all/modules/reol_bookmark/reol_bookmark.module
https://jira.itkdev.dk/browse/SUPP0RT-565
Improves handling of very long bookmark lists. Some user have hundreds of bookmarks …
=> SUPP0RT-565: Optimized handling of bookmark list

sites/all/modules/reol_use_loan/js/reader_standalone.js
Ticket: https://jira.itkdev.dk/browse/ER-1370
Added new setting parameters recommended by pub-hub.
=> ER-1370: Added extra url parameters to reader config

sites/all/modules/reol_base/reol_base.field.inc
https://jira.itkdev.dk/browse/ER-1301
Shows list of audio book narrators rather than just the first one.
Before:
After:
=> ER-1301: Added list of narrators

sites/all/modules/publizon/includes/publizon.admin.inc, sites/all/modules/reol_use_loan/reol_use_loan.module, sites/all/modules/reol_use_loan/templates/read.tpl.php
https://jira.itkdev.dk/browse/ER-1253
Adds more web reader settings (cf. https://docs.pubhub.dk/Reader/Pubhub_Reader_2.1.1.pdf).
=> ER-1253: Added web reader settings

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/SUPP0RT-667
- Display both body and lead in feed
=> SUPPORT-667: Change feed to display both body and lead for news

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
=> Revert "SUPPORT-667: Change feed to display both body and lead for news"

sites/all/modules/reol_field_carousel/reol_field_carousel.module, sites/all/themes/orwell/templates/ding_carousel.tpl.php
https://jira.itkdev.dk/browse/SUPP0RT-666
- SUPP0RT-666: Made carousel title required when search is set (and the other way around)
- SUPP0RT-666: Handled legacy carousel without title
=> SUPP0RT-666: Carousel title and search

.github/workflows/pr.yaml, .github/workflows/push.yaml
https://jira.itkdev.dk/browse/ER-1405
Removes use of `docker-compose run` in ations to prevent issues with nfs mounts.
=> Remove use of docker-compose in actions

sites/all/modules/reol_frontend/plugins/content_types/library_info.inc
https://jira.itkdev.dk/browse/SUPP0RT-737
Reports only loans on quota on user page.
=> SUPP0RT-737: Reported only quota loans

sites/all/modules/reol_frontend/plugins/content_types/library_info.inc
=> Revert "SUPP0RT-737: Reported only quota loans"

composer.json, profiles/ding2/modules/ding_reservation/ding_reservation.module, sites/all/modules/publizon/includes/publizon.reservation.inc, sites/all/modules/publizon/lib/Publizon.class.inc, sites/all/modules/publizon/lib/PublizonClient.class.inc, sites/all/modules/publizon/lib/PublizonLogger.class.inc, sites/all/modules/publizon/lib/PublizonNanoSoapClient.class.inc, sites/all/modules/publizon/lib/client/PublizonChecklistClient.class.inc, sites/all/modules/publizon/lib/client/PublizonLibraryClient.class.inc, sites/all/modules/publizon/lib/client/PublizonLoanClient.class.inc, sites/all/modules/publizon/lib/client/PublizonProductClient.class.inc, sites/all/modules/publizon/lib/client/PublizonReservationClient.class.inc, sites/all/modules/publizon/lib/client/PublizonUserClient.class.inc, sites/all/modules/publizon/lib/storage/PublizonChecklistItem.class.inc, sites/all/modules/publizon/lib/storage/PublizonLibrary.class.inc, sites/all/modules/publizon/lib/storage/PublizonLoan.class.inc, sites/all/modules/publizon/lib/storage/PublizonLoanStatus.class.inc, sites/all/modules/publizon/lib/storage/PublizonProduct.class.inc, sites/all/modules/publizon/lib/storage/PublizonReservation.class.inc, sites/all/modules/reol_loan/reol_loan.module, sites/all/themes/pratchett/templates/node--breol-video--view-mode--teaser.tpl.php
https://jira.itkdev.dk/browse/ER-1427
* Added types to publizon client
* Fixed reservations and missing parameter in ajax callback.
N/A
N/A
=> SERV-482: Added types to publizon client

.github/PULL_REQUEST_TEMPLATE.md
Cleans up the pull request template (by deleting leftover git diff conflict markers).
Automatic checks fails due to errors that are fixed in https://github.com/eReolen/base/pull/290.
=> Cleaned up pull request template

sites/all/modules/reol_app_feeds/src/Helper/NodeHelper.php
https://jira.itkdev.dk/browse/SUPP0RT-855
Loads nodes in the specified order.
=> SUPP0RT-855: Fixed ordering of nodes

sites/all/modules/publizon/includes/publizon.auth.inc, sites/all/modules/publizon/includes/publizon.loan.inc, sites/all/modules/publizon/includes/publizon.reservation.inc, sites/all/modules/publizon/lib/client/PublizonLibraryClient.class.inc, sites/all/modules/publizon/lib/client/PublizonLoanClient.class.inc, sites/all/modules/publizon/lib/client/PublizonReservationClient.class.inc, sites/all/modules/publizon/publizon.info, sites/all/modules/publizon/publizon.module
https://jira.itkdev.dk/browse/ER-1363
Add support for institution tags (from adgangsplatformen)
N/A
N/A
=> Added institution tags to reservation and loans

.gitignore, sites/all/modules/paragraphs/reol_link_paragraph/reol_link_paragraph.module
https://jira.itkdev.dk/browse/ER-1480
Allow aimated gifs
Before:
After:
=> There ya go

sites/all/themes/wille/assets/sass/component/_subject.scss
https://jira.itkdev.dk/browse/ER-1361
Add comment on swiper
N/A
=> Comment on swiper value

sites/all/modules/reol_carousel/js/reol_carousel.js
https://jira.itkdev.dk/browse/ER-1361
Change momentum.
Slide only one item on mobile.
N/A
=> Change momentum

sites/all/themes/orwell/template.php, sites/all/themes/wille/template.php
https://jira.itkdev.dk/browse/ER-1472
Prevents caching in fulltext parsing.
If your change affects the user interface you should include a screenshot of the result with the pull request.
=> Prevent caching in fulltext parsing

sites/all/modules/reol_app_feeds/src/Helper/FeedHelper.php, sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1494
Fixes handling of quotes (`&quot`) and other exotic characters in feed content.
=> ER-1494: Fixed handling of HTML entities in content

sites/all/modules/publizon/includes/publizon.bookmark.inc, sites/all/modules/reol_bookmark/reol_bookmark.module, sites/all/modules/reol_bookmark/reol_bookmark.pages.inc
https://jira.itkdev.dk/browse/SUPP0RT-1222
Sorts bookmarks by creation time.
If your code does not pass all the requirements on the checklist, you have to add a comment explaining why this change
=> SUPP0RT-1222: Sort bookmarks by creation time

sites/all/modules/publizon/includes/publizon.loan.inc, sites/all/modules/publizon/lib/storage/PublizonLoan.class.inc, sites/all/modules/reol_frontend/plugins/content_types/library_info.inc
https://jira.itkdev.dk/browse/ER-1498
Uses quota loan info from Publizon service rather than the quota information on the publication itself.
=> ER-1498: Used quota loan info from Publizon service

sites/all/modules/paragraphs/reol_link_paragraph/reol_link_paragraph.features.field_instance.inc, sites/all/modules/paragraphs/reol_link_paragraph/reol_link_paragraph.module, sites/all/themes/orwell/templates/paragraphs/paragraphs-item--linkbox.tpl.php, sites/all/themes/wille/templates/paragraphs/paragraphs-item--breol-linkbox--full.tpl.php
https://jira.itkdev.dk/browse/ER-1497
Enables links target on link box links. Related to changes in https://github.com/eReolen/ereolengo/pull/98.
=> ER-1497: Link target on link box

profiles/ding2/modules/contrib/entitycache/entitycache.api.php, profiles/ding2/modules/contrib/entitycache/entitycache.drush.inc, profiles/ding2/modules/contrib/entitycache/entitycache.info, profiles/ding2/modules/contrib/entitycache/entitycache.install, profiles/ding2/modules/contrib/entitycache/entitycache.module, profiles/ding2/modules/contrib/entitycache/entitycache.module.orig, profiles/ding2/modules/contrib/entitycache/entitycache.test, profiles/ding2/modules/contrib/entitycache/includes/entitycache.comment.inc, profiles/ding2/modules/contrib/entitycache/includes/entitycache.defaultentitycontroller.inc, profiles/ding2/modules/contrib/entitycache/includes/entitycache.entitycachecontrollerhelper.inc, profiles/ding2/modules/contrib/entitycache/includes/entitycache.entitycachecontrollerhelper.inc.orig, profiles/ding2/modules/contrib/entitycache/includes/entitycache.entitycacheentitycontrollerinterface.inc, profiles/ding2/modules/contrib/entitycache/includes/entitycache.node.inc, profiles/ding2/modules/contrib/entitycache/includes/entitycache.taxonomy.inc, profiles/ding2/modules/contrib/entitycache/includes/entitycache.user.inc
N/A
Security update of entity cache module
N/A
N/A
=> ITKDev: Updated entity cache module

sites/all/themes/orwell/templates/search/search-block-form.tpl.php
https://jira.itkdev.dk/browse/ER-1495
Remove theme search toggle
=> ER-1495: Show only the search input (Hide theme search toggle)

sites/all/modules/publizon/publizon.module
https://jira.itkdev.dk/browse/ER-1521
Set mobile and email as unchecked by default
=> ER-1521: Set mobile and email as unchecked by default

sites/all/modules/reol_app_feeds/src/Helper/ParagraphHelper.php
https://jira.itkdev.dk/browse/ER-1513
Decodes numeric entities in HTML (which `html_entity_decode` in PHP 7.4 apparently does not).
=> ER-1513: Decoded numeric entities

sites/all/themes/orwell/template.php
https://jira.itkdev.dk/browse/SUPP0RT-1333
Fixes handling of a link that went under the radar [the first time](https://github.com/eReolen/base/pull/334).
=> SUPP0RT-1333: Fixed the missing link

sites/all/modules/ereol_article/assets/admin.css, sites/all/modules/ereol_article/ereol_article.features.field_base.inc, sites/all/modules/ereol_article/ereol_article.features.field_instance.inc, sites/all/modules/ereol_article/ereol_article.features.inc, sites/all/modules/ereol_article/ereol_article.features.taxonomy.inc, sites/all/modules/ereol_article/ereol_article.module, sites/all/modules/ereol_article/ereol_article.strongarm.inc, sites/all/modules/ereol_article/ereol_article.views_default.inc, sites/all/modules/reol_carousel/js/reol_carousel.js
https://leantime.itkdev.dk/#/tickets/showTicket/769
Adds article carousel and list filters based on article type and subjects.
=> 769: Carousel article filters

sites/all/themes/wille/templates/user/library_info.tpl.php
https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/1269
Ad back stuff that was removed in https://github.com/eReolen/base/pull/321/files
=> Add back stuff from https://github.com/eReolen/base/pull/321/files

CHANGELOG.md, sites/all/themes/wille/overlay/overlay.js
Please add a link to the ticket being addressed by this change.
Please include a short description of the suggested change and the reasoning behind the approach you have chosen.
If your change affects the user interface you should include a screenshot of the result with the pull request.
=> Cachebust overlay assets
